language: node_js
node_js:
  - "10"

addons:
  sonarcloud:
    organization: "monzond-github"
    token: $SONAR_TOKEN

before_script:
  - npm run setup
  - npm run build
  - npm run build-templates

script:
  - npm test
  - sonar-scanner

after_success:
  - npm pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "epjClubManager-*.tgz"
    skip_cleanup: true
    on:
      tags: true
      
notifications:
  slack: epj-clubmanager:$SLACK_TOKEN
