language: node_js
node_js:
  - "10"

addons:
  sonarcloud:
    organization: "monzond-github"
    token: $SONAR_TOKEN

before_script:
  - npm run setup

script:
  - npm run ci
  - if [ $TRAVIS_PULL_REQUEST == false ]; then sonar-scanner; fi

after_success:
  - npm pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "epjClubManager-*.tgz"
    skip_cleanup: true
    on:
      tags: true
      
notifications:
  slack: epj-clubmanager:$SLACK_TOKEN
